routes/admin.php
<?php

Route::get('Admin2020',  function(){
    return redirect()->route('admin.login');
});

Route::group(['namespace' => 'Auth'], function(){
    # Login Routes
    Route::get('login',     'LoginController@showLoginForm')->name('login');
    Route::post('login',    'LoginController@login');
    Route::post('logout',   'LoginController@logout')->name('logout');

});

Route::group(['middleware' => 'auth:admin'],function (){

    # dashboard
    Route::get('/dashboard',                'DashboardController@index')->name('dashboard');

    # admin update password
    Route::get('change-password',           'DashboardController@changePassword')->name('change-password');
    Route::patch('update-password',         'DashboardController@updatePassword')->name('update-password');



    # FAQ
    Route::patch('faq/change-status',        'FaqController@changeStatus')->name('faq.change-status');
    Route::post('faq/delete',               'FaqController@delete')->name('faq.delete');
    Route::post('faq/bulk-delete',          'FaqController@bulkDelete')->name('faq.bulk-delete');
    Route::resource('faq',                  'FaqController');

    # Customer
    Route::resources([
        'category'      => CategoryController::class,
        'customers'     => UserController::class,
        'restaurants'   => RestaurantController::class,
        'cms'           => CmsController::class,
        'notification'  => NotificationController::class,
        'settings'      => SettingController::class,
        'promo-codes'   => PromoCodeController::class,
        'addon'         => AddonController::class,
        'item'          => ItemController::class,
        'table'         => TableController::class,
        'order'         => OrderController::class,
    ]);

    # category
    Route::patch('category-change-status',       'CategoryController@changeStatus')->name('category.change_status');

    # Customer
    Route::patch('customer-change-status',       'UserController@changeStatus')->name('customers.change_status');

    # Restaurant
    Route::patch('restaurant-change-status',     'RestaurantController@changeStatus')->name('restaurants.change_status');

    #Cms
    Route::patch('cms-change-status',       'CmsController@changeStatus')->name('cms.change_status');

    #PromoCode
    Route::patch('promo-codes-change-status',       'PromoCodeController@changeStatus')->name('promo-codes.change_status');
    Route::get('promo-codes-users',                 'PromoCodeController@promoCodeUser')->name('promo-codes.users');
    Route::patch('promo-codes-users-delete',        'PromoCodeController@destroyUserPromoCode')->name('promo-codes.users_delete');

    #Addon
    Route::patch('addon-change-status',       'AddonController@changeStatus')->name('addon.change_status');

    #Item
    Route::patch('item-change-status',       'ItemController@changeStatus')->name('item.change_status');
    Route::get('category-list',              'ItemController@categoryList')->name('category.list');

    #Table
    Route::patch('table-change-status',       'TableController@changeStatus')->name('table.change_status');

    #Order
    Route::patch('order-complete',       'OrderController@orderCompleted')->name('order.order_complete');
    Route::patch('order-ready-to-take',       'OrderController@orderReadyToTake')->name('order.ready_to_take');

});

?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('admin-panel',  function(){
    return redirect()->route('admin.login');
});

// Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact-us', 'HomeController@contact')->name('contact');
Route::get('/about-us', 'HomeController@about')->name('about');
Route::get('/product-details', 'HomeController@product_details')->name('product_details');
Route::get('/services', 'HomeController@services')->name('services');

// Route::get('/custom-link','Api\CommonController@customLink');
// // ios applink
// Route::get('apple-app-site-association','Api\CommonController@appleAppsiteAssociation');

resources/views/layouts/footer.blade.php
<footer class="footer">
</footer>

resources/views/layouts/header.blade.php
<div class="topbar">

    <div class="topbar-left	d-none d-lg-block">
        <div class="text-center">
            <a href="{{ route('admin.dashboard') }}" class="logo">
                @isset($adminSetting['image'])
                    <img src="{{ asset('storage/'.$adminSetting['image']) }}" height="50" alt="logo" class="rounded-circle">
                @endisset
            </a>
        </div>
    </div>

    <nav class="navbar-custom">

        <ul class="list-inline float-right mb-0">
            {{-- <li class="list-inline-item notification-list dropdown d-none d-sm-inline-block">
                <form role="search" class="app-search">
                    <div class="form-group mb-0">
                        <input type="text" class="form-control" placeholder="Search..">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </li> --}}

            <li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none waves-effect nav-user" data-toggle="dropdown" href="#" role="button"
                    aria-haspopup="true" aria-expanded="true">
                    @isset($adminSetting['image'])
                        <img src="{{ asset('storage/'.$adminSetting['image']) }}" height="50" alt="logo" class="rounded-circle">
                    @endisset
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated profile-dropdown ">
                    <a class="dropdown-item" href="{{ route('admin.change-password') }}"><i class="mdi mdi-lock-open-outline m-r-5 text-muted"></i> Change Password</a>

                    <a class="dropdown-item" href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="mdi mdi-logout m-r-5 text-muted"></i> Logout</a>

                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>

        </ul>

        <ul class="list-inline menu-left mb-0">
            <li class="list-inline-item">
                <button type="button" class="button-menu-mobile open-left waves-effect">
                    <i class="ion-navicon"></i>
                </button>
            </li>
        </ul>

        <div class="clearfix"></div>

    </nav>

</div>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
        <title>@yield('page_title') | Admin </title>
        <meta content="Admin Dashboard" name="description" />
        <meta content="ThemeDesign" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="csrf-token" content={{csrf_token()}}>

        <link rel="shortcut icon" href="{{ asset('assets/images/favicon.ico') }}">

        <!--Morris Chart CSS -->
        <link rel="stylesheet" href="{{ asset('assets/plugins/morris/morris.css') }}">

        <link href="{{ asset('assets/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
        <link href="{{ asset('assets/css/icons.css')}}" rel="stylesheet" type="text/css">
        <link href="{{ asset('assets/css/style.css')}}" rel="stylesheet" type="text/css">

        <link href="{{ asset('assets/plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('assets/plugins/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('assets/plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />

        <link href="{{ asset('assets/plugins/sweet-alert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
        @stack('page_css')
        <link href="{{ asset('assets/css/custom.css')}}" rel="stylesheet" type="text/css">
    </head>


    <body class="fixed-left">
        @php
            $adminSetting = adminSetting();
        @endphp
        <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
        @guest @yield('content') @else
        <div id="wrapper">

            @include('layouts.sidebar')

            <div class="content-page">

                <div class="content">

                    @include('layouts.header')

                    <div class="page-content-wrapper ">

                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-sm-12">
                                    @yield('page_head')

                                    <h5 class="page-title">@yield('page_title')</h5>
                                </div>
                            </div>

                            @yield('content')

                        </div>

                    </div>

                </div>

                @include('layouts.footer')

            </div>

        </div>
        @endguest
        <script src="{{ asset('assets/js/jquery.min.js') }}"></script>
        <script src="{{ asset('assets/js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ asset('assets/js/modernizr.min.js') }}"></script>
        <script src="{{ asset('assets/js/detect.js') }}"></script>
        <script src="{{ asset('assets/js/fastclick.js') }}"></script>
        <script src="{{ asset('assets/js/jquery.slimscroll.js') }}"></script>
        <script src="{{ asset('assets/js/jquery.blockUI.js') }}"></script>
        <script src="{{ asset('assets/js/waves.js') }}"></script>
        <script src="{{ asset('assets/js/jquery.nicescroll.js') }}"></script>
        <script src="{{ asset('assets/js/jquery.scrollTo.min.js') }}"></script>

        <!--Morris Chart-->
        <script src="{{ asset('assets/plugins/morris/morris.min.js') }}"></script>
        <script src="{{ asset('assets/plugins/raphael/raphael-min.js') }}"></script>

        <!-- dashboard -->
        {{-- <script src="{{ asset('assets/pages/dashboard.js') }}"></script> --}}

        <!-- App js -->
        <script src="{{ asset('assets/js/app.js') }}"></script>

        <script src="{{ asset('assets/plugins/parsleyjs/parsley.min.js') }}"></script>

        <!-- datatable -->
        <script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap4.min.j')}}s"></script>

        <script src="{{ asset('assets/plugins/sweet-alert2/sweetalert2.min.js') }}"></script>
        <script src="{{ asset('assets/pages/sweet-alert.init.js') }}"></script>

        <script src="{{ asset('assets/plugins/tinymce/tinymce.min.js')}}"></script>

        <script>
            $(document).ready(function() {
                $('form').parsley();
            });
            window.setTimeout(function() {
                $(".alert").fadeTo(500, 0).slideUp(500, function(){
                    $(this).remove();
                });
            }, 3000);
            $(document).ready(function () {
                if($("#answer").length > 0){
                    tinymce.init({
                        selector: "textarea#answer",
                        theme: "modern",
                        height:300,
                        plugins: [
                            "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                            "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                            "save table contextmenu directionality emoticons template paste textcolor"
                        ],


                    });
                }
            });
            $('#select_all').on('click', function(){
                if($('.select_row').is(':checked')){
                    $('input[type="checkbox"]').prop('checked', false);
                } else {
                    $('input[type="checkbox"]').prop('checked', true);
                }
            });
        </script>
        @stack('page_scripts')
        <script src="{{ asset('assets/js/custom.js') }}"></script>
    </body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="left side-menu">
    <button type="button" class="button-menu-mobile button-menu-mobile-topbar open-left waves-effect">
        <i class="ion-close"></i>
    </button>

    <div class="left-side-logo d-block d-lg-none">
        <div class="text-center">
            @isset($adminSetting['image'])
                <a href="{{ route('admin.dashboard') }}" class="logo"><img src="{{ asset('storage/'.$adminSetting['image']) }}" height="20" alt="logo"></a>
            @endisset
        </div>
    </div>

    <div class="sidebar-inner slimscrollleft">

        <div id="sidebar-menu">
            <ul>
                <li>
                    <a href="{{ route('admin.dashboard') }}" class="waves-effect">
                        <i class="dripicons-meter"></i>
                        <span> Dashboard </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.addon.index') }}" class="waves-effect">
                        <i class="fa fa-list"></i>
                        <span> Addon </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.category.index') }}" class="waves-effect">
                        <i class="fa fa-list"></i>
                        <span> Category </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.restaurants.index') }}" class="waves-effect">
                        <i class="fa fa-cutlery"></i>
                        <span> Restaurant </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.item.index') }}" class="waves-effect">
                        <i class="fa fa-list-alt"></i>
                        <span> Item </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.table.index') }}" class="waves-effect">
                        <i class="fa fa-table"></i>
                        <span> Table </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.order.index') }}" class="waves-effect">
                        <i class="fa fa-first-order"></i>
                        <span> Order </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.customers.index') }}" class="waves-effect">
                        <i class="fa fa-users"></i>
                        <span> Customer </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.promo-codes.index') }}" class="waves-effect">
                        <i class="fa fa-gift"></i>
                        <span> Promo Code </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.promo-codes.users') }}" class="waves-effect">
                        <i class="fa fa-ticket"></i>
                        <span> Promo Code Users </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.notification.index') }}" class="waves-effect">
                        <i class="fa fa-bell"></i>
                        <span> Notification </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.cms.index') }}" class="waves-effect">
                        <i class="fa fa-grav"></i>
                        <span> Cms </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.settings.index') }}" class="waves-effect">
                        <i class="fa fa-cog"></i>
                        <span> Setting </span>
                    </a>
                </li>

            </ul>
        </div>
        <div class="clearfix"></div>
    </div> <!-- end sidebarinner -->
</div>